### ISSUE TITLE
bestehende Funktionen prüfen und ggfs. bereinigen

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-formtools#1]

**Comment by dmolineus** [comment]
Die Erweiterung bietet ja die Möglichkeit im CE/FE Modul ein Custom Template zu definieren. Seit Contao 4 werden die Templates nach dem Modultyp gefiltert, sprich es werden nur Tempaltes angezeigt, die dem Schema `ce_form` entsprechen. Dies widerspricht dem Namen der Formular-Templates, die ja mit "form_wrapper" beginnen. Sprich, die Funktion ist de facto nicht wirklich nutzbar, wenn man das Namensschema einnhält.

Seit C4 gibt es ja auch die Option im Formular selbst ein Template zu hinterlegen. Daher die Frage, ob diese Funktion überhaupt noch gebraucht wird oder weg kann?

**Comment by frontendschlampe** [comment]
kann weg, wenn folgende Funktionalität vorhanden:

Wenn eine Weiterleitungsseite eingestellt ist, dann muss die Erfolgsmeldung nicht ausgegeben werden

**Comment by dmolineus** [comment]
Wie besprochen ist die Funktion nun entfernt. Die Erfolgsmeldung wird nur generiert, wenn keine Jump-To Page definiert wurde.
