### ISSUE TITLE
Individuelle Fehlermeldungen

### ISSUE THREAD

**Issue by Ynda** [hofff/contao-formtools#12]
Hallo zusammen,

ich habe diese Erweiterung installiert in der Hoffnung, individuelle Fehlertexte einzutragen. Leider finde ich die entsprechenden Felder nicht, wo das passieren soll? Bin ich blind oder wo versteckt sich das?
Ich habe mir auch schon den Quellcode angeschaut, um evtl. etwas herauszufinden. Ich kann im DCA ein solches Feld nicht entdecken, obwohl es einen EventListener src/EventListener/Hook/AddErrorMessageListener.php gibt.
Kann mich da bitte jemand erhellen?

Danke

**Comment by frontendschlampe** [comment]
Die individuellen Meldungen gelten für das gesamte Formular, damit man keine separate Bestätigungsseite benötigt. Es hat nichts mit den Fehlermeldungen eines einzelnen Feldes zu tun. So steht es m.E. auch in der README: _add custom error/success message before form (useful when no page redirect is defined)_

**Comment by Ynda** [comment]
Dann habe ich es wohl falsch verstanden. Sorry dafür.

Gruß Andy




Von: Nicky Hoff ***@***.***>
Gesendet: Montag, 11. März 2024 11:44
An: hofff/contao-formtools ***@***.***>
Cc: Andreas Bohlig ***@***.***>; Author ***@***.***>
Betreff: Re: [hofff/contao-formtools] Individuelle Fehlermeldungen (Issue #12)


Die individuellen Meldungen gelten für das gesamte Formular, damit man keine separate Bestätigungsseite benötigt. Es hat nichts mit den Fehlermeldungen eines einzelnen Feldes zu tun. So steht es m.E. auch in der README: add custom error/success message before form (useful when no page redirect is defined)
