### ISSUE TITLE
Meldung auf der selben Seite nach Absenden des Formulares über erfolgreichen Versand oder Fehlers

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-formtools#2]
Bisher wurde das immer über das Template geregelt, aber das war sehr unvorteilhaft, weil die Meldungen entsprechend angepasst werden mussten. Des weiteren funktioniert die Templatelösung nicht mehr in Contao 4.x, da die Session nach dem Absenden nicht mehr vorhanden ist. Es wäre also gut, wenn man 2 Checkboxen im Formular hat, wo man die Meldungen für einen Fehler oder den erfolgreichen Versand des Formulares pflegen kann.

**Comment by dmolineus** [comment]
Wie besprochen Ausgabe vor dem form_wrapper Template per Hook

**Comment by dmolineus** [comment]
Implementiert mit ee180a09a240389569add1252d9fd9c40d47239a
