### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by PaoloB** [hofff/contao-formtools#6]
I installed the extension and there is no Italian translation.
Can I help you and do the Italian translation?
How can I do the Italian translation?

Thanks

**Comment by frontendschlampe** [comment]
Hey @PaoloB ... yes, you can help with the Italian translation. Just make a Pull Request for translation. We will merge it asap. :-)

**Comment by PaoloB** [comment]
Perfect. 
I did the translation.
I hope I have done well. I have never made a Pull Request.

**Comment by frontendschlampe** [comment]
Great ... no problem, it's very easy ... you have to clone this repo into your account - add and change the files you want in your clone - when you're ready just make the PR ...

**Comment by PaoloB** [comment]
Thanks,
yes I did it this way.
Everything should be correct.

**Comment by frontendschlampe** [comment]
öhm ... yes ... but there's no PR https://github.com/hofff/contao-formtools/pulls

**Comment by frontendschlampe** [comment]
you have to make the pull request: open your repo, switch to your branch and klick on Pull Request on the right side, make a comment and hit the button "Create Pull Request"

**Comment by PaoloB** [comment]
well, I did.

**Comment by frontendschlampe** [comment]
great ... I will check asap. and if everything is fine, we will release an new version ...

**Comment by frontendschlampe** [comment]
fixed in 2fe43e8f38e75feb1fc27b3fd17fb4e9b5465d2a - release 3.0.1
