### ISSUE TITLE
Formular hebt das Caching einer Seite nicht auf?

### ISSUE THREAD

**Issue by MacKP** [hofff/contao-formtools#8]
Ich hab das jetzt noch nicht weiter durchgetestet, allerdings hatte ich auf einer Seite (cache Aktiv -> Server und Browser) in einer C4.4 Installation das Problem, dass ein Kunde direkt die Erfolgsmeldung gesehen hat und nicht das Formular. Nachdem ich den Cache gelöscht und ausgeschaltet hatte war das Problem nicht mehr da.
Normalerweise hebt Contao ja das Caching auf, wenn ein Formular integriert ist. Ist das durch die Erwieterung eventuell nicht mehr so?

Viele Grüße

**Comment by frontendschlampe** [comment]
ui ... das müssten wir mal prüfen ... danke für den Hinweis

**Comment by frontendschlampe** [comment]
Lag jetzt leider eine Weile. Wie besprochen, können wir es beide nicht mehr so richtig nachvollziehen. Ich schließe das Ticket erstmal und wenn uns das Problem nochmal über den Weg laufen sollte, dann öffnen wir es nochmal. :-)
